name: Deploy Steps

on:
  workflow_dispatch:

env:
  AZURE_SUBSCRIPTION_ID: 5a6208ea-211a-40d5-b26e-b89603eada13
  AZURE_RESOURCEGROUP_ID: rg-crm-dev-eastus
  AZURE_RESOURCE_GROUP: rg-crm-dev-eastus
  AZURE_TENANT_ID: 548d26ab-8caa-49e1-97c2-a1b1a06cc39c
  AZURE_ENV_NAME: "emt-crm-dev-01"
  CONTAINER_ENV_NAME: cae-crm-dev-01
  ACRNAME: cremtcrmdev01
  AZURE_CHAT_API_KEY: azurekeyhere
  AZURE_CHAT_DEPLOYMENT_NAME: deploynamehere
  AZURE_CHAT_ENDPOINT: endpointhere

jobs:
  deploy-global:
    runs-on: ubuntu-latest
    steps:
    - name: Display information
      run: |
        echo "Event Name: ${{ github.event_name }}"
        echo "Ref: ${{ github.ref }}"
        echo "SHA: ${{ github.sha }}"
        echo "Actor: ${{ github.actor }}"
        echo "Workflow: ${{ github.workflow }}"
        echo "Run ID: ${{ github.run_id }}"
        echo "Run number: ${{ github.run_number }}"

  deploy-region:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: [eastus, brazilsouth, northeurope, eastasia]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install azd
      uses: Azure/setup-azd@v0.1.0

    - name: Install .NET Aspire workload
      run: dotnet workload install aspire

    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: '{"clientId": "${{ secrets.CLIENTID }}", "clientSecret": "${{ secrets.CLIENTSECRET }}", "subscriptionId": "${{ env.AZURE_SUBSCRIPTION_ID }}", "tenantId": "${{ secrets.TENANTID }}" }'

    - name: Login to AZD
      run: azd auth login --client-id "${{ secrets.CLIENTID }}" --client-secret "${{secrets.CLIENTSECRET}}" --tenant-id "${{ secrets.TENANTID }}"

    - name: Enable resource scoped deployments
      run: azd config set alpha.resourceGroupDeployments on

    # - name: Deploy other resources not handled by aspire
    #   run: |
    #     az deployment group create \
    #       --resource-group ${{ env.AZURE_RESOURCEGROUP_ID }} \
    #       --template-file bicep/main.bicep \
    #       --parameters location=${{ matrix.region }} tenantId=${{ secrets.TENANTID }}

    - name: Echo Azure Location
      env:
        AZURE_LOCATION: ${{ matrix.region }}    
      run: echo "AZURE_LOCATION is $AZURE_LOCATION"
   
    - name: Display current path
      run: pwd

    - name: List directory contents
      run: ls -la

    - name: Provision Aspire Infrastructure
      env:
        AZURE_LOCATION: ${{ matrix.region }}
      run: azd --debug provision --no-prompt --cwd AspireSample.AppHost
      working-directory: AspireSample.AppHost

    - name: Deploy Aspire Application
      env:
        AZURE_LOCATION: ${{ matrix.region }}
      run: azd deploy --no-prompt     
